# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# --- General options --- #

# Site settings
title: My Blog # ex. Trice的小博客
name: username # ex. CuiYiming
email: example@gmail.com
location: GuangZhou, China # ex. GuangZhou, China
# company: MyCompany
company_url: my_company_website
github_url: https://github.com/username # ex. https://github.com/cuiyiming007
github_username: username # ex. cuiyiming007
description: description
favicon: favicon.png # Image must be in assets/images
repository: cuiyiming007/cuiyiming007.github.io # ex. cuiyiming007/cuiyiming007.github.io
bigimg: [/assets/images/home/background1.jpg, /assets/images/home/background2.jpg]

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://cuiyiming007.github.io
url: http://localhost:4000
# url: https://username.github.io

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home
    title: 首页

  -
    href: /open-source
    label: Open-Source
    title: 开源

  -
    href: /blog
    label: Blog
    title: 博客

  -
    href: /bookmark
    label: Bookmark
    title: 书签

  -
    href: /about
    label: About
    title: 关于我

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      gh-badge: [star, watch, fork]
  -
    scope:
      path: "" # all files
    values:
      layout: "page"

kramdown:
  input: GFM
  enable_coderay: true

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  rss: true
  email: "example@gmail.com"
  # facebook: yourname
  github: yourname
  # weibo: yourname
  # twitter: yourname
#  reddit: yourname
#  google-plus: yourname
#  linkedin: yourname
#  xing: yourname
#  stackoverflow: "yourname"
#  snapchat: yourname
#  instagram: yourname
#  youtube: user/yourname
#  spotify: yourname
#  telephone: +14159998888
#  steam: yourname
#  twitch: yourname
#  yelp: yourname


# --- Comments --- #
#livere
livere: xxx # data-uid ex. MTAyMC80NDQ1Ni8yMDk4O111
# Disque
# disque:  # ex. cuiyiming.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'xxx'  # ex. UA-140385529-1


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, Kotlin, C, C++, SQLite]
# skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS]
skill_mobile_app_keywords: [Android, Flutter, ReactNative]
